import '@/styles/globals.css'
import { inter } from '@/utils/fonts/fontsGoogle'
import Providers from '@/utils/provider'

export const metadata = {
  title: 'AL-Quran | Awesome',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="id">
      <body className={`${inter.className}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
